name: angular

on:
  push:
    branches: [ main ]

jobs:
  build:

    name: Build and test
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
    
    defaults:
      run:
        working-directory: ./angular

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          
      - run: npm ci
    
      - name: Install win-node-env
        run: npm install -g win-node-env
      
      - run: npm run build --if-present
      - run: npm test
