name: angular

on:
  push:
    branches: [ main ]

jobs:
  build:

    name: Building and testing on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    
    defaults:
      run:
        working-directory: ./angular

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          
      - run: npm ci
    
      - name: Install win-node-env
        run: npm install -g win-node-env
      
      - run: npm run build --if-present
      - run: npm test
